### ISSUE TITLE
Add capability to execute UDF on a single record

### ISSUE THREAD

**Issue by v-noskov** [aerospike/php-client#14]
Hi,

Please enhance the client by adding the capability to execute User Defined Functions (UDF) on a single record. The corresponding feature, 'Client::execute_udf,' already exists in the underlying Rust client.

**Comment by vmsachin** [comment]
@v-noskov Yes, we will be adding this functionalities in the coming releases.

**Comment by vmsachin** [comment]
@v-noskov this feature had been added with the v0.5.0-beta release.
