### ISSUE TITLE
Not able to Access sock file from apache user and asld service is also not created

### ISSUE THREAD

**Issue by piyush-bansal1989** [aerospike/php-client#31]
Hi Team

I'm reaching out to bring to your attention two issues I'm encountering with the Aerospike connection manager:

**Socket File Access**: After executing the **make** file within the **aerospike-connection-manager** directory, the socket file created through this is unable to access by the Apache user, **transport error throws**
**Missing asld.service**: The **make daemonize** command executed under **aerospike-connection-manager** is not creating the asld.service file at given path. following is the output of the command

```
rm -f asld
rm -f memprofile.out profile.out
rm -rf proto asld_kvs.pb.go asld_kvs_grpc.pb.go
find . -name "*.coverprofile" -exec rm {} +
protoc --go-grpc_out=. --go_out=. asld_kvs.proto --experimental_allow_proto3_optional
go build -ldflags="-X 'main.version=1.0.1'" -o  asld -o asld -v .
sudo cp asld /usr/local/bin/asld
sudo cp asld.toml /etc/asld.toml
sudo cp asld.service /lib/systemd/system/asld.service
cp: cannot stat 'asld.service': No such file or directory
make: *** [Makefile:34: daemonize] Error 1
```

**Comment by vmsachin** [comment]
Hi @piyush-bansal1989 ,

Thanks for bringing this to our attention. We have identified the issue. Will release in fix in the upcoming patch release scheduled.

**Comment by vmsachin** [comment]
@piyush-bansal1989 has been fixed with v1.0.2 release.

**Comment by piyush-bansal1989** [comment]
@vmsachin : Would you please help me understand what changes have been done?, I'm facing the same exception whenc connecting through **transport error**

**Comment by vmsachin** [comment]
@piyush-bansal1989 it was a naming change, we hadn't updated the service name in the make file for aerospike connection manager. 
Are you able to build and run the Aerospike connection manager? 
If you are seeing transport error, I'm guessing you are. Could you try and run the php file as root user ( `sudo php ... `)

**Comment by piyush-bansal1989** [comment]
> @piyush-bansal1989 it was a naming change, we hadn't updated the service name in the make file for aerospike connection manager. Are you able to build and run the Aerospike connection manager? If you are seeing transport error, I'm guessing you are. Could you try and run the php file as root user ( `sudo php ... `)


@vmsachin : Yes I'm able to build and run the Aerospike connection manager. It's working when I run it through terminal **with and without sudo**. When I tried to run through apache (web server), it throws Exception **transport error**.
